module.exports =
  dir: "./app/"
  index: "./app/index.html"
  vendorjs: "./app/vendor.js"
  js: "./app/js/**/*.js"
  css: "./app/css/**/*.css"
  partials: "./app/partials/**/*.html"
  image: "./app/image/**/*.+(webp|png|jpg|jpeg|gif)"
  copy: []
  output: "./dist/"
  isWatching: false
